net: socket::{set,get}_reuseaddr() should not be virtual
socket is using pimpl pattern. and it is not derived by any class.
so there is no need to mark the getter/setter of reuseaddr as virtual.
also, if we would make any of its method virtual, we should mark its
destructor virtual as well. so this change also silences a GCC warning
like:

seastar/include/seastar/net/api.hh:212:7: error: ‘class seastar::socket’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
  212 | class socket {
      |       ^~~~~~

Signed-off-by: Kefu Chai <kchai@redhat.com>